name: Sync Fork
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          
      - name: Add upstream repository and sync
        run: |
          git remote add upstream https://github.com/remix-run/remix.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          cp -r .github/workflows/sync.yml /tmp/
          mkdir -p .github/workflows/
          cp /tmp/sync.yml .github/workflows/
          find .github/workflows/ -type f ! -name 'sync.yml' -delete
          
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          git push "https://${{ secrets.GH_PERSONAL_TOKEN }}@github.com/${{ github.repository }}" main
